---
#  _________________________
# < Vlad configuration file >
#  -------------------------
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#
# Change settings here to control how Vlad sets up your box.
#
# See the full list of available variables here.
# http://vlad-docs.readthedocs.org/en/latest/usage/variables/
#

# Webserver settings
  webserver_hostname: 'drupal.local'
  webserver_hostname_aliases:
  - 'www.drupal.local'
#  - 'www.example.com'

# Vagrantfile configuration
  boxipaddress: "192.168.101.101"
  boxname: "vlad"
  host_synced_folder: "../docroot"
# or on Windows
#  host_synced_folder: "C:\\docroot"

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

  adminer_install: true

  apache_install: true

  imagemagick_install: false

  mailcatcher_install: false

  memcached_install: true

  munin_install: false

  mysql_install: true

  node_install: false

  php_install: true

  pimpmylog_install: false

  redis_install: false

  ruby_install: false # Ruby is required by MailCatcher

  sendmail_install: true

  solr_install: true

  varnish_install: false # If you turn this off then make sure you set the http_port to be 80.

  xhprof_install: false

# HTTP port for the web server. If you choose to install Varnish then you might want to set this to "8080"
  http_port: 80

# HTTP port for the Varnish cache
  varnish_http_port: 80


# migl custom config
  custom_provision: false
  php_version: 5.4
  use_host_id: true
  drupal_solr_package: "apachesolr"
  add_index_file: false